### PR TITLE
Adds support on Android to connect to a private room.

### PR DESCRIPTION
**Pull request by anyercastillo**
### Description
Adds support on Android to connect to a private room by scanning a QR Code.

### Video
https://github.com/getditto/demoapp-chat/assets/5747647/8e86783d-f9fa-4a8c-9529-dea109be46d9

### Out of scope but nice to have
- Generate QR Code
- Remove rooms

### For developers
In order for me to understand the feature I made a diagram with the high level architecture. I would like to share with you.
diagram

### CODE REVIEW

**Comment by magicwave** [comment]
Nice diagram! Are the documents in the diagram messages?

**Comment by magicwave** [comment]
Does this PR supercede an earlier private rooms feature PR by abunur?

**Comment by anyercastillo** [comment]
> Does this PR supercede an earlier private rooms feature PR by abunur?

This is another implementation of the feature.

**Review by okdistribute — APPROVED** [review]
Great work!

**Pull request merged**
