### PR TITLE
Feature/copyright update

### PR DESCRIPTION
**Pull request by abunur**
updated copyright template and applied to entire project
also removes reference to authentication, this seems to have been merged in by accident? authentication is separate branch that should not be merged to main

### CODE REVIEW

**Comment by phatblat** [comment]
I missed it on the [last PR](https://github.com/getditto/demoapp-chat/pull/47/files#diff-42e41a4c8b01a42ec53868cfc32c95e246afc1672a057dc6de6bc1b32342211fR4) but the smart quotes `“”` around Software look weird compared to the original quotes `""`.

```diff
-(the "Software")
+(the “Software”)

Did those come from an external editor?

**Review by phatblat — APPROVED** [review]

**Comment by abunur** [comment]
> I missed it on the [last PR](https://github.com/getditto/demoapp-chat/pull/47/files#diff-42e41a4c8b01a42ec53868cfc32c95e246afc1672a057dc6de6bc1b32342211fR4) but the smart quotes `“”` around Software look weird compared to the original quotes `""`.
> 
> ```diff
> -(the "Software")
> +(the “Software”)
> ```
> 
> Did those come from an external editor?

No, actually I copy/pasted from the original copyright text we had in one of the files, into the template, but all within Android Studio (Mac OS). I'll see if I can change them from my keyboard or not...

**Comment by abunur** [comment]
@phatblat I just pushed an update, do they look normal, now?

**Comment by phatblat** [comment]
yes, much better 👌🏻

**Pull request merged**
