### PR TITLE
✨⛙ Merge Attachments feature with Multiple chat rooms feature on Android

### PR DESCRIPTION
**Pull request by abunur**
Attachments feature was developed and merged prior to multiple chat rooms feature; the two branches were far out of sync
This PR:
(1) merges the two features safely
(2) fixes Context leak and other issues in the Attachments feature
(3) merging this PR will supersede / remove the need for a separate PR already made to the develop branch which is only for the multiple chat rooms feature

IMG_2241 2

### CODE REVIEW

**Comment by magicwave** [comment]
Android Studio Android Studio Hedgehog | 2023.1.1 Canary 13 fails building this PR branch with this error:
```Build file '/Users/ericturner/Programming/Ditto/Private/demoapp-chat/Android/app/build.gradle' line: 33

A problem occurred evaluating project ':app'.
> Parameter specified as non-null is null: method com.android.build.gradle.internal.dsl.BuildType.buildConfigField, parameter value
```, essentially complaining that no value for `DITTO_AUTH_PROVIDER` key could be found in the environment files.

iOS main branch version uses offlineOnly and no authentication, so this branch, as a candidate for main, should likewise build without authentication requirements.

**Comment by abunur** [comment]
@magicwave thanks, credential variables removed from Gradle

**Comment by magicwave** [comment]
These changes to the iOS app come with this PR that should be removed:
	iOS/DittoChat/Env 1.19.23 PM.swift
	iOS/DittoChat/Env 10.26.06 AM.swift
	iOS/DittoChat/Env 2.15.17 PM.swift
	iOS/DittoChat/Env 2.21.45 PM.swift
	iOS/DittoChat/Env 2.46.40 PM.swift
	iOS/DittoChat/Env 3.59.50 PM.swift
	iOS/DittoChat/Models 5.16.36 PM/
	iOS/DittoChat/Screens 5.17.00 PM/
	iOS/DittoChat/Screens/ChatScreen/MessageBubbleView_delete.swift
	iOS/DittoChat/Utilities 5.17.00 PM/

**Comment by abunur** [comment]
> These changes to the iOS app come with this PR that should be removed:
> iOS/DittoChat/Env 1.19.23 PM.swift
> iOS/DittoChat/Env 10.26.06 AM.swift
> iOS/DittoChat/Env 2.15.17 PM.swift
> iOS/DittoChat/Env 2.21.45 PM.swift
> iOS/DittoChat/Env 2.46.40 PM.swift
> iOS/DittoChat/Env 3.59.50 PM.swift
> iOS/DittoChat/Models 5.16.36 PM/
> iOS/DittoChat/Screens 5.17.00 PM/
> iOS/DittoChat/Screens/ChatScreen/MessageBubbleView_delete.swift
> iOS/DittoChat/Utilities 5.17.00 PM/

Is there a simple way to remove those commits via git? Or should we cherry pick from Main, if so can you list the files touched rather than the commits themselves, then I can easily just grab the latest version of the file from Main

thanks

**Comment by phatblat** [comment]
> A problem occurred evaluating project ':app'.
> Parameter specified as non-null is null: method com.android.build.gradle.internal.dsl.BuildType.buildConfigField, parameter value
```, essentially complaining that no value for `DITTO_AUTH_PROVIDER` key could be found in the environment files.

Is this app using the android Gradle plugin v8? I believe the build config generation is opt-in starting in 8

**Comment by abunur** [comment]
> > A problem occurred evaluating project ':app'.
> > Parameter specified as non-null is null: method com.android.build.gradle.internal.dsl.BuildType.buildConfigField, parameter value
> > ```, essentially complaining that no value for `DITTO_AUTH_PROVIDER` key could be found in the environment files.
> 
> Is this app using the android Gradle plugin v8? I believe the build config generation is opt-in starting in 8

It's using Gradle 8.0.2
These parameters are variables we created in order to store secret keys for the app in a separate file that is in the .gitignore
There is another version of the app that uses authentication, so it has two extra variables defined. 
@magicwave was correct in saying this version should not define those variables

**Comment by magicwave** [comment]
> > These changes to the iOS app come with this PR that should be removed:
> > iOS/DittoChat/Env 1.19.23 PM.swift
> > iOS/DittoChat/Env 10.26.06 AM.swift
> > iOS/DittoChat/Env 2.15.17 PM.swift
> > iOS/DittoChat/Env 2.21.45 PM.swift
> > iOS/DittoChat/Env 2.46.40 PM.swift
> > iOS/DittoChat/Env 3.59.50 PM.swift
> > iOS/DittoChat/Models 5.16.36 PM/
> > iOS/DittoChat/Screens 5.17.00 PM/
> > iOS/DittoChat/Screens/ChatScreen/MessageBubbleView_delete.swift
> > iOS/DittoChat/Utilities 5.17.00 PM/
> 
> Is there a simple way to remove those commits via git? Or should we cherry pick from Main, if so can you list the files touched rather than the commits themselves, then I can easily just grab the latest version of the file from Main
> 
> thanks

you would have to remove these files and commit the deletes.

**Comment by abunur** [comment]
> > > These changes to the iOS app come with this PR that should be removed:
> > > iOS/DittoChat/Env 1.19.23 PM.swift
> > > iOS/DittoChat/Env 10.26.06 AM.swift
> > > iOS/DittoChat/Env 2.15.17 PM.swift
> > > iOS/DittoChat/Env 2.21.45 PM.swift
> > > iOS/DittoChat/Env 2.46.40 PM.swift
> > > iOS/DittoChat/Env 3.59.50 PM.swift
> > > iOS/DittoChat/Models 5.16.36 PM/
> > > iOS/DittoChat/Screens 5.17.00 PM/
> > > iOS/DittoChat/Screens/ChatScreen/MessageBubbleView_delete.swift
> > > iOS/DittoChat/Utilities 5.17.00 PM/
> > 
> > 
> > Is there a simple way to remove those commits via git? Or should we cherry pick from Main, if so can you list the files touched rather than the commits themselves, then I can easily just grab the latest version of the file from Main
> > thanks
> 
> you would have to remove these files and commit the deletes.

I'm not following? If the files need to be deleted, that means they should actually have been in the .gitignore
If it's files that were changed that should not have been touched, then please reference which files were touched, and then they can be restored (not deleted) from main branch

thanks

**Comment by magicwave** [comment]
I'm hitting this error now:
/Users/ericturner/Programming/Ditto/Private/demoapp-chat/Android/app/build/generated/source/buildConfig/debug/live/dittolive/chat/BuildConfig.java:13: error: ';' expected
  public static final String DITTO_APP_ID = 22389e28-9590-4cbf-b683-b3ac5ab2269e;

**Comment by abunur** [comment]
> I'm hitting this error now:
> /Users/ericturner/Programming/Ditto/Private/demoapp-chat/Android/app/build/generated/source/buildConfig/debug/live/dittolive/chat/BuildConfig.java:13: error: ';' expected
> public static final String DITTO_APP_ID = 22389e28-9590-4cbf-b683-b3ac5ab2269e;

Try **File -> Invalidate Caches** with the restart option. That error is coming from generated code, not source

**Comment by magicwave** [comment]
Fails after invalidating all caches and restart. Build config looks like missing quotes on hardcoded values?
```
public final class BuildConfig {
  public static final boolean DEBUG = Boolean.parseBoolean("true");
  public static final String APPLICATION_ID = "live.dittolive.chat";
  public static final String BUILD_TYPE = "debug";
  public static final int VERSION_CODE = 24;
  public static final String VERSION_NAME = "1.0";
  // Field from build type: debug
  public static final String DITTO_APP_ID = 22389e28-9590-4cbf-b683-b3ac5ab2269e;
  // Field from build type: debug
  public static final String DITTO_LICENSE_TOKEN = 62479eb9-9f23-46cf-907b-ab5309d46369;
}
```

**Comment by phatblat** [comment]
> It's using Gradle 8.0.2

The version of the Android Gradle Plugin is what matters.

### Gradle Version

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.6
```

### Android Gradle Plugin (AGP) Version

```
$ ./gradlew buildEnvironment | grep 'com.android.tools.build:gradle'
|    \--- com.android.tools.build:gradle:7.4.1
|         +--- com.android.tools.build:gradle-settings-api:7.4.1
|         \--- com.android.tools.build:gradle-api:7.4.1
|    \--- com.android.tools.build:gradle:7.4.1 (*)
```

### Generated `BuildConfig` Class

> AGP 8.0 doesn't generate BuildConfig by default. You need to specify this option using the DSL in the projects where you need it.

https://developer.android.com/build/releases/gradle-plugin#default-changes

FYI, you can still have AGP generate the `BuildConfig` class if you add`android.defaults.buildfeatures.buildconfig = true` to `gradle.properties1. See getditto/ditto#8991 for my WIP work to upgrade to AGP 8 in the monorepo.

https://github.com/getditto/ditto/pull/8991/files#diff-3ab34fb625c346ec8377e7204444075ec41563ca1227c9a231df8c966386de89R45

**Comment by phatblat** [comment]
This app is using AGP [`8.0.2`](https://github.com/getditto/demoapp-chat/blob/main/Android/build.gradle#L23) and Gradle [`8.0`](https://github.com/getditto/demoapp-chat/blob/main/Android/gradle/wrapper/gradle-wrapper.properties#L28)

**Comment by magicwave** [comment]
So, in language even a little tiny baby could understand, what should I do, and/or, should this be a fix in the commit or is it just a machine-local configuration?

**Comment by phatblat** [comment]
It appears that the project _does_ have `android.defaults.buildfeatures.buildconfig=true` enabled. I would try deleting that `BuildConfig.java` file and running the build again. Are you building in Android Studio?

**Comment by magicwave** [comment]
> It appears that the project _does_ have `android.defaults.buildfeatures.buildconfig=true` enabled. I would try deleting that `BuildConfig.java` file and running the build again. Are you building in Android Studio?

yes, using Android Studio Android Studio Hedgehog | 2023.1.1 Canary 13 preview, as advised by Fuad. Thanks, I'll give 'er a try.

**Comment by abunur** [comment]
> > It appears that the project _does_ have `android.defaults.buildfeatures.buildconfig=true` enabled. I would try deleting that `BuildConfig.java` file and running the build again. Are you building in Android Studio?
> 
> yes, using Android Studio Android Studio Hedgehog | 2023.1.1 Canary 13 preview, as advised by Fuad. Thanks, I'll give 'er a try. [UPDATE] No joy, same error message. I invalidated all caches, deleted BuildConfig.java and retried.

@magicwave I was on one version older of AS than you. I updated, found some very strange build issues, and deleted a couple of unused files, and was able to build. I pushed my changes to this branch, can you try a build again and see if it works for you now? If it fails, try invalidate caches/restart and then try building again. 

thanks

**Comment by magicwave** [comment]
> @magicwave I was on one version older of AS than you. I updated, found some very strange build issues, and deleted a couple of unused files, and was able to build. I pushed my changes to this branch, can you try a build again and see if it works for you now? If it fails, try invalidate caches/restart and then try building again.
> thanks
I deleted the BuildConfig.java file, invalidated all caches, restarted. The gradle build completed successfully (I guess that's what happened; the console showed a bunch of activity at AS start and then ended with a success message.) Then I tried to build to a device and halted at the exact same error as before.

**Comment by abunur** [comment]
update: we were able to get it to build on @magicwave 's Mac, in his Environment variable the quotes were missing

**Review by magicwave — APPROVED** [review]

**Comment by magicwave** [comment]
I approved the PR but before merging, please remove the iOS files that were added to this branch somehow (listed above) and push a commit with the deletes.

**Comment by magicwave** [comment]
@abunur - I approved the PR but before merging, please remove the iOS files that were added to this branch somehow (listed above) and push a commit with the deletes.

**Comment by abunur** [comment]
> @abunur - I approved the PR but before merging, please remove the iOS files that were added to this branch somehow (listed above) and push a commit with the deletes.

The entire iOS directory and its contents have been restored from `main`

**Pull request merged**
