### PR TITLE
✨Private Rooms on Android

### PR DESCRIPTION
**Pull request by abunur**
This enables joining a private room
To test:
1. create a private room on an iOS device. Go into the chat room, and display the QR code for the room
2. on Android, go to side menu, hit the QR scan button 
Screenshot 2023-07-24 at 4 40 12 PM
3. scan the QR code displayed on the iOS device, with the Android device
4. test cross platform chatting in private rooms :P 

This PR:
- tracks private chat rooms in local database on Android (Room)
- provides a source code sample for customers demonstrating Repository pattern, accessing local database, Ditto SDK, and exchanging data between local Sqlite database and Ditto
- demonstrates all of this using Dependency Injection via Hilt

This PR builds on top of previous PRs which:
- introduced multiple public rooms support on Android
- merged public rooms support branch with Android Attachments

### CODE REVIEW

**Comment by magicwave** [comment]
This branch fails to rebase onto main.

**Comment by magicwave** [comment]
Seems to be no way to add a private room from Android

**Comment by magicwave** [comment]
All private rooms added by iOS and joined via QR code are named `some private room` in the list

**Comment by abunur** [comment]
> This branch fails to rebase onto main.

are you sure? Github is not complaining about any merge conflicts, and locally I have no issue with it

**Comment by abunur** [comment]
> Seems to be no way to add a private room from Android

This PR only allows joining via QR code, which is currently only available on iOS

**Comment by abunur** [comment]
> All private rooms added by iOS and joined via QR code are named `some private room` in the list

This is a known issue. See last commit, there is a known race condition which causes the local store chat room to be created before joining the mesh version of the chat room. Therefore the room name is hard coded to a default name.

**Comment by okdistribute** [comment]
Superseded by https://github.com/getditto/demoapp-chat/pull/85

**Pull request closed without merging**
