### PR TITLE
Update to DQL

### PR DESCRIPTION
**Pull request by texasRanger09**
Blocked by https://github.com/getditto/ditto/issues/11410

### CODE REVIEW

**Comment by ErikEverson** [comment]
This is early but I did notice a Bug with it just so you know to keep an eye out for it. 
New rooms are replicated to Big Peer (if using onlinePlayground) but will not show up on a connected SP that didn't create the room.

**Comment by okdistribute** [comment]
Let's have @magicwave wrap this up, Walker is busy right now

**Comment by magicwave** [comment]
> This is early but I did notice a Bug with it just so you know to keep an eye out for it. New rooms are replicated to Big Peer (if using onlinePlayground) but will not show up on a connected SP that didn't create the room.

@ErikEverson - can you elaborate a bit?

1. The chat app was designed and implemented to demo offline-only chat, without forethought of a mesh including Big Peer.

2. There are public rooms and private rooms. Private rooms are "private" only by obfuscation, i.e., an un-guessable collection name that is shared between peers in close proximity via QR code. Where Big Peer becomes a container for all collections, "private' un-guessable room and message collections will be accessible in BP.

It certainly may be a bug, but as reported, it's not clear what is the use case where BP is involved, and what is the expectation that is unmet, indicating a bug. 

Because public rooms are universally visible/accessible in the "public" collection we would expect public rooms to be visible/accessible to all small peers on local and greater meshes that include BP. So if we're not seeing public rooms on all peers that are connected to a mesh, including or not including BP, that is definitely a bug. 

However, we would not expect private rooms to appear in the rooms list on the app for peers which haven't been joined via a QR scan, even where BP is part of the mesh, since peers only subscribe to private rooms they know about, i.e. rooms they have created or have been invited to via scan.

**Comment by ErikEverson** [comment]
I will reproduce the issue and update here with more info so you have everything you need to diagnose it.

**Comment by okdistribute** [comment]
As per yesterday's conversation @kndoshn will drive this to close

**Comment by kndoshn** [comment]
📝 This PR is currently blocked by this issue: https://github.com/getditto/ditto/issues/13117

**Review by kndoshn — APPROVED** [review]

**Comment by kndoshn** [comment]
I fixed and tested this branch, and it all looks good now.
I'm planning to merge this at the end of this week unless someone else wants to point out something.

**Pull request merged**
