### PR TITLE
iOS - bump DittoSwift SDK to 4.2.1

### PR DESCRIPTION
**Pull request by magicwave**

### CODE REVIEW

**Review by texasRanger09 — APPROVED** [review]

**Review by kndoshn — APPROVED** [review]

**Comment by magicwave** [comment]
Should I merge this or maybe update with latest SDK? I wonder if the package configuration should be `4.0.0 - upToNextMajorVersion` and leave it at that? Anyone can use Xcode to `update to latest package versions`.

**Comment by okdistribute** [comment]
Yeah that sounds like a good idea

**Comment by kndoshn** [comment]
@magicwave Would you migrate this to 4.3.1?

**Comment by okdistribute** [comment]
Yes, let's try to always use the latest version on all of our demo apps because we use them as a way to root out issues. We have been a bit slow about this recently but they should be updated as soon as possible. Ideally they would be in CI so this wouldn't have to be a manual process.

**Pull request closed without merging**
